function [] = Photon_47_1 ()
% Repository group: 06_laboratory_phantom_models
% Version role: analysis or follow-up variant
%
% Research note: This file is retained as a documented historical version.
% Review configuration, external data dependencies, and output paths before use.
% Impact of Tumor/Signal on DPF/PPF Series Simulations
% this version: Analyzing data generated by Photon_47.m


clc
close all
set(0,'DefaultFigureWindowStyle','docked')
format long

set_of_TiO2 = [0.50, 2.50, 5.0, 7.5]; % percents of TiO2
set_of_indk = [0.01, 0.05, 0.25, 1.0, 5.0, 10.0, 20.0]; % percents of India ink
exp_data = [13.7753	207.923	102.388	52.4519
            11.3449	103.615	36.8395	43.3181
            7.32753	29.1057	17.6853	14.7035
            2.21560	8.16695	4.77848	3.50841
            1.74571	7.01301	4.01610	2.91083
            1.51530	6.60495	3.71168	2.67495
            1.50993	6.73614	3.66488	2.67495];
N_bins = 151; d_edges = linspace(0,sqrt(8.^2+5.^2),N_bins+1);

figure(1)
idx_x = 1:length(set_of_indk);
for i_TiO2 = 1:length(set_of_TiO2)
    plot(1:length(idx_x),-log(exp_data(idx_x,i_TiO2)./exp_data(1,i_TiO2)),'LineWidth',2,'DisplayName',['TiO_2 = ',num2str(set_of_TiO2(i_TiO2)),' g/L']), hold on
end
xlabel('India Ink (v/v, %)'), set(gca,'xtick',idx_x), set(gca,'xticklabel',set_of_indk(idx_x))
ylabel('OD (log(I/I_{C=0.01%}), a.u)')
set(gca,'FontSize',24), grid on, hold off
legend('show','Location','southeast')
clearvars idx_x i_TiO2


figure(2)
subplot(1,2,1)
idx_x = 2:length(set_of_indk);
for i_TiO2 = 1:length(set_of_TiO2)
    plot(1:length(idx_x),-log(exp_data(idx_x,i_TiO2)./exp_data(1,i_TiO2))./set_of_indk(idx_x).','Marker','s','LineWidth',2,'DisplayName',['TiO_2 = ',num2str(set_of_TiO2(i_TiO2)),' g/L']), hold on
end
xlabel('India Ink (v/v, %)'), set(gca,'xtick',idx_x), set(gca,'xticklabel',set_of_indk(idx_x))
ylabel('OD/C (1/%)')
set(gca,'FontSize',24), grid on, hold off
legend('show','Location','northeast')
clearvars idx_x i_TiO2
subplot(1,2,2)
idx_x = 2:length(set_of_indk);
for i_TiO2 = 1:length(set_of_TiO2)
    semilogx(set_of_indk(idx_x),-log(exp_data(idx_x,i_TiO2)./exp_data(1,i_TiO2))./set_of_indk(idx_x).','Marker','s','LineWidth',2,'DisplayName',['TiO_2 = ',num2str(set_of_TiO2(i_TiO2)),' g/L']), hold on
end
xlabel('India Ink (v/v, %)'), set(gca,'xtick',set_of_indk(idx_x)), set(gca,'xticklabel',set_of_indk(idx_x))
ylabel('OD/C (1/%)')
set(gca,'FontSize',24), grid on, hold off
legend('show','Location','northeast')
clearvars idx_x i_TiO2

figure(3)
for i_indk = 1:length(set_of_indk)
    plot(set_of_TiO2,-log(exp_data(i_indk,:)./exp_data(i_indk,1))./set_of_TiO2,'LineWidth',2,'DisplayName',['India ink = ',num2str(set_of_indk(i_indk)),' %']), hold on
end
xlabel('TiO2 (g/L)'), set(gca,'xtick',set_of_TiO2)
ylabel('OD/C (L/g)')
set(gca,'FontSize',24), grid on, hold off
legend('show','Location','southeast')
clearvars idx_x i_indk






set_of_ds = nan(length(set_of_TiO2),length(set_of_indk),length(d_edges)-1);
set_of_Is = nan(length(set_of_TiO2),length(set_of_indk),length(d_edges)-1);
% simulation analysis
for i_TiO2 = 1:length(set_of_TiO2)
    for i_indk = 1:length(set_of_indk)
        the_TiO2 = set_of_TiO2(i_TiO2);
        the_indk = set_of_indk(i_indk);
        data = load(['/home/kaiser/BackUp/Dropbox/research/2.NIRs Project/code/DB/Photon_47_TiO2_',num2str(the_TiO2),'_Indik_',num2str(the_indk),'.mat']);
        fun_x = @mean; fun_y = @sum; TheOutFun = @(x)(-log(x));
        x_temp = sqrt(...
            (data.p_in(:,1)-data.p_ot(:,1)).^2+ ...
            (data.p_in(:,2)-data.p_ot(:,2)).^2+ ...
            (data.p_in(:,3)-data.p_ot(:,3)).^2);
        y_temp = data.w_ot/data.no_of_photons;
        idx_exl = data.p_ot(:,1)<=3;
        x_temp = x_temp(idx_exl); y_temp = y_temp(idx_exl); clearvars idx_exl

        [~,~,index_in] = histcounts(x_temp,d_edges);
        x_bind = accumarray(index_in,x_temp,[],fun_x,nan);
        y_bind = accumarray(index_in,y_temp,[],fun_y,nan);
        set_of_ds(i_TiO2,i_indk,1:length(x_bind)) = x_bind;
        set_of_Is(i_TiO2,i_indk,1:length(y_bind)) = y_bind;
        set_of_Is(i_TiO2,i_indk,:) = set_of_Is(i_TiO2,i_indk,:).*0.8./2./pi./set_of_ds(i_TiO2,i_indk,:); % we have a 0.8 cm detector

        TheColor = [(i_TiO2-1)/(length(set_of_TiO2)-1),0,(i_indk-1)/(length(set_of_indk)-1)];
        figure(4), plot(squeeze(set_of_ds(i_TiO2,i_indk,:)),-log(squeeze(set_of_Is(i_TiO2,i_indk,:))),'Color',TheColor,'DisplayName',['TiO_2=',num2str(the_TiO2),', indk=',num2str(the_indk)]), hold on
        clearvars the_TiO2 the_indk data TheColor
        clearvars index_in x_temp y_temp fun_x fun_y TheOutFun
    end
end
xlabel('d (cm)'),
ylabel('OD (log(I/I_{C=0.01%}), a.u)')
set(gca,'FontSize',18), grid on, hold off
legend('show', 'Location', 'northeast', 'NumColumns', 4);
clearvars i_indk i_TiO2



figure(5)
idx_x = 1:length(set_of_indk);
[~,idx_d] = min(abs(d_edges(2:end-0)/2+d_edges(1:end-1)/2 - 6)); idx_d = idx_d-3:idx_d+3;
subplot(1,2,1)
for i_TiO2 = 1:length(set_of_TiO2)
    plot(1:length(idx_x),mean(-log(set_of_Is(i_TiO2,idx_x,idx_d)./set_of_Is(i_TiO2,1,idx_d)),3),'LineWidth',2,'DisplayName',['TiO_2 = ',num2str(set_of_TiO2(i_TiO2)),' g/L']), hold on
end
title('simulation')
xlabel('India Ink (v/v, %)'), set(gca,'xtick',idx_x), set(gca,'xticklabel',set_of_indk(idx_x))
ylabel('OD (log(I/I_{C=0.01%}), a.u)')
set(gca,'FontSize',24), grid on, hold off, axis square
legend('show','Location','southeast')

subplot(1,2,2)
for i_TiO2 = 1:length(set_of_TiO2)
    plot(1:length(idx_x),-log(exp_data(idx_x,i_TiO2)./exp_data(1,i_TiO2)),'LineWidth',2,'DisplayName',['TiO_2 = ',num2str(set_of_TiO2(i_TiO2)),' g/L']), hold on
end
title('data')
xlabel('India Ink (v/v, %)'), set(gca,'xtick',idx_x), set(gca,'xticklabel',set_of_indk(idx_x))
ylabel('OD (log(I/I_{C=0.01%}), a.u)')
set(gca,'FontSize',24), grid on, hold off, axis square
legend('show','Location','southeast')
clearvars idx_x i_TiO2 idx_x
end
